[REGRESSION] _h_m_t_x.py", line 60, in compile metrics = sum(metrics,[])
TypeError: can only concatenate list (not "tuple") to list

Fixes https://github.com/behdad/fonttools/issues/30